config/routes.rb
Conceptor::Application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  resources :users
  resources :sessions
  resources :concepts

  root 'concepts#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    
    if (user)
      can :create, Concept
      can :manage, Concept do |concept|
        concept && concept.user == user
      end
    end
  end
end

app/models/concept.rb
class Concept < ActiveRecord::Base
  belongs_to :user
  
  validates_length_of :name, within: 3..120
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :concepts
  
  #validates_uniqueness_of :email
  validates_uniqueness_of :name
  validates_length_of :password, within: 3..32
  #validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates_format_of :name, with: /[a-zA-Z0-9]+/, message: "only allows letters"
  validates_format_of :password, with: /[a-zA-Z0-9]+/, message: "only allows letters"
  validates_length_of :name, within: 3..32, message: "name lenght between 3 - 32"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
  # GET /concepts
  def index
    @concepts = Concept.all
  end

  # GET /concepts/1
  def show
    @concept = Concept.find(params[:id])
  end

  # GET /concepts/new
  def new
    authorize! :create, Concept
    @concept = Concept.new
  end

  # POST /concepts
  def create
    authorize! :create, Concept
    @concept = Concept.new(concept_params)
    @concept.user = current_user

    respond_to do |format|
      if @concept.save
        format.html { redirect_to @concept, notice: 'Concept was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # GET /concepts/1/edit
  def edit
    @concept = Concept.find(params[:id])
    authorize! :manage, @concept
  end

  # PATCH/PUT /concepts/1
  def update
    @concept = Concept.find(params[:id])
    authorize! :manage, @concept
    
    respond_to do |format|
      if @concept.update(concept_params)
        format.html { redirect_to @concept, notice: 'Concept was updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /concepts/1
  def destroy
    @concept = Concept.find(params[:id])
    authorize! :manage, @concept
    @concept.destroy
    
    respond_to do |format|
      format.html { redirect_to concepts_url, notice: 'Concept was deleted.' }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def concept_params
      params.require(:concept).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else 
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params.require(:user).permit(:email, :password, :password_confirmation, :name))
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for singing up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/concepts/_form.html.erb
<%= form_for(@concept) do |f| %>
  <% if @concept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concept.errors.count, "error") %> prohibited this concept from being saved:</h2>

      <ul>
      <% @concept.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/concepts/edit.html.erb
<h1>Editing concept</h1>

<%= render 'form' %>

<%= link_to 'Show', @concept %> |
<%= link_to 'Back', concepts_path %>

app/views/concepts/index.html.erb
<h1>Listing concepts</h1>

<table>
  <thead>
    <tr>
      <th>Rank</th>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @concepts.each do |concept| %>
      <tr>
        <td>0</td>
        <td><%= link_to concept.name, concept %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if can? :create, Concept %>
  <%= link_to 'New Concept', new_concept_path %>
<% end %>

app/views/concepts/new.html.erb
<h1>New concept</h1>

<%= render 'form' %>

<%= link_to 'Back', concepts_path %>

app/views/concepts/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @concept.name %>
</p>
<p>
  <strong>Creator:</strong>
  <% if @concept.user %>
    <%= @concept.user.name %>
  <% else %>
      not available
  <% end%>
</p>

<% if can? :manage, @concept %>
  <%= link_to 'Edit', edit_concept_path(@concept) %> |
  <%= link_to 'Delete', @concept, method: :delete, data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', concepts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Conceptor</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1><%= link_to 'Conceptor', root_url %></h1>
  
	<p>
    <% if current_user %>
      Logged in as <%= current_user.name %> (<%= link_to "Log Out", logout_path %>)
    <% else %>
	    <%= link_to "Sign Up", signup_path %> or 
      <%= link_to "Log In", login_path %>
    <% end%>
	</p>

  <p>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
  </p>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>